### ISSUE TITLE
Please give an example

### ISSUE THREAD

**Issue by mekk55** [mkliu/cordova-plugin-appsettings#1]
Hello,

Would you please give me example or demo to create setting page on phonegap android app with you plugin. ?

Thank you
Umpol

**Comment by mkliu** [comment]
AppSettings.get(
		    function(value) {
		        alert("Value: " + JSON.stringify(value));
		    },
		    function(error) {
		        alert("Error! " + JSON.stringify(error));
		}, ["Preference1", "Preference2"]);

**Comment by mkliu** [comment]
ah, sorry i tried to dig up one but couldn't find anymore. But this should be enough? 
		AppSettings.get(
		    function(value) {
		        alert("Value: " + JSON.stringify(value));
		    },
		    function(error) {
		        alert("Error! " + JSON.stringify(error));
		}, ["Preference1", "Preference2"]);

**Comment by mkliu** [comment]
ah, sorry i tried to dig up one but couldn't find anymore. But this should be enough? 
        AppSettings.get(
        function(value) {
        alert("Value: " + JSON.stringify(value));
        },
        function(error) {
        alert("Error! " + JSON.stringify(error));
        }, ["Preference1", "Preference2"]);
