### ISSUE TITLE
Inconsistency in casing between Android and iOS

### ISSUE THREAD

**Issue by jacobg** [mkliu/cordova-plugin-appsettings#2]
In iOS, all keys are lower-cased, particularly when AppSettings.get callback. But in Android, the dictionary object sent in callback does not have lowercase key names.

In general, I don't understand why keys are lower-cased in any case. Why not just leave them as is?

**Comment by mkliu** [comment]
i don't have iOS so didn't test :)  That code was directly forked from https://github.com/apache/cordova-labs/tree/cdvtest. Feel free to fix it and send me a pull request

**Comment by jacobg** [comment]
I ended up removing all lowercasing from both iOS and Android. I don't know why it's there.

But if you want lowercasing, then in order to do it consistently, Android needs to look like this on line 24:

``` java
options.put(key.toLowerCase(Locale.getDefault()), keyvalue);
```

**Comment by mkliu** [comment]
@jacobg i added you as collaborator. Feel free to push your change
