### ISSUE TITLE
Need GitHub releases and others

### ISSUE THREAD

**Issue by micky2be** [mkliu/cordova-plugin-appsettings#4]
Please make sure to tag your release on GitHub, so we could install a specific version from the GitHub url.

Also try to push your releases on NPM. Would be very useful.

**Comment by mkliu** [comment]
already in npm
https://www.npmjs.com/package/cordova-plugin-appsettings

**Comment by micky2be** [comment]
Doesn't work the way expected.
The name on npm and in your plugin.xml need to be the same.

If I run `cordova plugin add cordova-plugin-appsettings --save` it will add the following in my config.xml:
`<plugin name="com.wizky.cordova.appsettings" spec="1.0.0" />`
Which points to the Cordova Plugin Registry with the wrong version
