### ISSUE TITLE
Discrepancy between npm and plugin.xml

### ISSUE THREAD

**Issue by micky2be** [mkliu/cordova-plugin-appsettings#5]
It's impossible to use the npm version of the plugin by running `cordova plugin add cordova-plugin-appsettings --save` since it's gonna write the wrong information in the config.xml file.

Name and versioning should be the same in package.json and plugin.xml

**Comment by mkliu** [comment]
@micky2be i'm not using Cordova anymore, send me a pull request, i'll happily merge it

**Comment by micky2be** [comment]
@mkliu If you are not using Cordova anymore could you put me and/or @jrouault as a maintainer on both GitHub and NPM please.

**Comment by mkliu** [comment]
@micky2be done. I gave up on Ionic and Cordova. Moving to React now.
